# -*- coding: utf-8 -*-
"""Day8workshop(classification).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGI8pzPBSPBRxpTeQmeEYltKTtbOLuqp
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

df = pd.read_csv("WineQT.csv")

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)

print(df.head())

print("\n")
print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(df.info())

print("\n")
print("="*60)
print("STATISTICAL SUMMARY")
print("="*60)

print(df.describe())

print("\n")
print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

print("\n")
print("="*60)
print("DUPLICATES")
print("="*60)

print(df.duplicated().sum())

print(df.columns)

df = df.drop("citric acid", axis=1)

print("\n")
print("="*60)
print("TARGET CLASSES")
print("="*60)

print(df["density"].value_counts())

X = df.drop("quality", axis=1)

y = df["quality"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\n")
print("="*60)
print("MODEL ACCURACY")
print("="*60)

print(f"Accuracy : {accuracy*100:.2f}%")

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("\n")
print("="*60)
print("CLASSIFICATION REPORT")
print("="*60)

print(classification_report(
    y_test,
    y_pred,
    target_names=[str(i) for i in sorted(df["quality"].unique())]
))

cm = confusion_matrix(y_test, y_pred)

print("\n")
print("="*60)
print("CONFUSION MATRIX")
print("="*60)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=sorted(df["quality"].unique())
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

importance = np.mean(np.abs(model.coef_), axis=0)

feature_names = X.columns

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("\n")
print("="*60)
print("FEATURE IMPORTANCE")
print("="*60)

print(importance_df)

plt.figure(figsize=(8,5))

plt.bar(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Importance")

plt.xticks(rotation=20)

plt.show()



new_wine = [[
    7.4, 0.70, 0.00, 1.9,
    0.076, 11.0, 34.0,
    0.9978, 3.51, 0.56, 9.4
]]

prediction = model.predict(new_wine)

print("Predicted Wine Quality :", prediction[0])

wines = [

    [7.4, 0.70, 0.00, 1.9, 0.076, 11.0, 34.0, 0.9978, 3.51, 0.56, 9.4],

    [7.8, 0.88, 0.00, 2.6, 0.098, 25.0, 67.0, 0.9968, 3.20, 0.68, 9.8],

    [6.5, 0.39, 0.23, 8.3, 0.051, 28.0, 91.0, 0.9952, 3.44, 0.55, 12.1]

]

predictions = model.predict(wines)

print("\nMultiple Predictions")

for i in range(len(wines)):
    print(f"Wine {i+1} --> Predicted Quality: {predictions[i]}")

import joblib

joblib.dump(model, "wine_model.pkl")

print("\nModel Saved Successfully.")

import joblib

loaded_model = joblib.load("wine_model.pkl")

sample = [[
    7.4, 0.70, 0.00, 1.9,
    0.076, 11.0, 34.0,
    0.9978, 3.51, 0.56, 9.4
]]

pred = loaded_model.predict(sample)

print("\nPrediction Using Saved Model")
print("Predicted Wine Quality:", pred[0])